package transcript

import (
	"path/filepath"
	"strings"
)

// readClaude reads a Claude Code session file: one JSON object per line,
// `type` user or assistant, `message.content` a string or content blocks
// (text, tool_use, tool_result). Sub-agent (sidechain) and injected (isMeta)
// lines are not the conversation and are skipped.
func readClaude(path string) ([]Session, error) {
	b := newBuilder()
	b.s.ID = strings.TrimSuffix(filepath.Base(path), ".jsonl")
	err := eachLine(path, func(e obj) {
		typ := str(e, "type")
		if typ != "user" && typ != "assistant" {
			return
		}
		if ep := str(e, "entrypoint"); ep != "" && b.s.Origin == "" {
			b.s.Origin = ep
		}
		if e["isMeta"] == true || e["isSidechain"] == true || e["isCompactSummary"] == true {
			return
		}
		at := toTime(e["timestamp"])
		if id := str(e, "sessionId"); id != "" {
			b.s.ID = id
		}
		if cwd := str(e, "cwd"); cwd != "" && b.s.Cwd == "" {
			b.s.Cwd = cwd
		}
		msg := asObj(e["message"])
		if msg == nil {
			return
		}
		if m := str(msg, "model"); m != "" && m != "<synthetic>" {
			b.s.Model = m
		}
		content := msg["content"]
		if s, ok := content.(string); ok {
			if typ == "user" && !commandNoise(s) {
				b.say(RoleUser, s, at)
			} else if typ == "assistant" {
				b.say(RoleAssistant, s, at)
			}
			return
		}
		var text []string
		var calls []obj
		for _, blk := range asList(content) {
			bo := asObj(blk)
			switch str(bo, "type") {
			case "text":
				text = append(text, str(bo, "text"))
			case "tool_use":
				calls = append(calls, bo)
			case "tool_result":
				b.result(str(bo, "tool_use_id"), bo["is_error"] == true)
			}
		}
		joined := strings.Join(text, "\n")
		switch {
		case typ == "user" && !commandNoise(joined):
			b.say(RoleUser, joined, at)
		case typ == "assistant":
			b.say(RoleAssistant, joined, at)
		}
		for _, bo := range calls { // what was said, then what was run
			b.tool(str(bo, "id"), str(bo, "name"), targetOf(bo["input"]), at)
		}
	})
	return b.session(), err
}

// commandNoise is text Claude Code writes for its own slash-command plumbing.
func commandNoise(s string) bool {
	s = strings.TrimSpace(s)
	return strings.HasPrefix(s, "<command-") || strings.HasPrefix(s, "<local-command-") ||
		strings.HasPrefix(s, "Caveat: The messages below were generated by the user while running local commands")
}
