package identity

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"math/big"
	"net/http"
	"net/http/httptest"
	"net/netip"
	"testing"
	"time"
)

// mTLS is tested through a real handshake rather than a synthesised
// tls.ConnectionState, because the property that matters is not "the code
// reads a field" — it is that the certificate was VERIFIED against a CA the
// operator configured. A hand-built ConnectionState would let the test set
// VerifiedChains itself and prove nothing.

func certOf(t *testing.T, tmpl, parent *x509.Certificate, parentKey *ecdsa.PrivateKey) (
	*x509.Certificate, *ecdsa.PrivateKey, []byte) {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	signer, signerKey := parent, parentKey
	if signer == nil {
		signer, signerKey = tmpl, key // self-signed
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, signer, &key.PublicKey, signerKey)
	if err != nil {
		t.Fatal(err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		t.Fatal(err)
	}
	return cert, key, der
}

// mtlsHarness stands up a TLS server that requires and verifies a client
// certificate, and returns a client holding one.
func mtlsHarness(t *testing.T, clientCN string, clientEmail []string) (
	*httptest.Server, *http.Client, chan Identity, chan bool) {
	t.Helper()
	caTmpl := &x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{CommonName: "grimoire-test-ca"},
		NotBefore:    time.Now().Add(-time.Hour), NotAfter: time.Now().Add(time.Hour),
		IsCA: true, KeyUsage: x509.KeyUsageCertSign, BasicConstraintsValid: true,
	}
	ca, caKey, caDER := certOf(t, caTmpl, nil, nil)

	clientTmpl := &x509.Certificate{
		SerialNumber:   big.NewInt(2),
		Subject:        pkix.Name{CommonName: clientCN},
		EmailAddresses: clientEmail,
		NotBefore:      time.Now().Add(-time.Hour), NotAfter: time.Now().Add(time.Hour),
		KeyUsage:    x509.KeyUsageDigitalSignature,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
	}
	_, clientKey, clientDER := certOf(t, clientTmpl, ca, caKey)

	pool := x509.NewCertPool()
	pool.AddCert(ca)

	ids := make(chan Identity, 4)
	oks := make(chan bool, 4)
	srv := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		peer, _ := PeerAddr(r)
		id, ok := (&MTLS{}).Identify(peer, r)
		ids <- id
		oks <- ok
		w.WriteHeader(http.StatusOK)
	}))
	srv.TLS = &tls.Config{ClientAuth: tls.RequireAndVerifyClientCert, ClientCAs: pool}
	srv.StartTLS()
	t.Cleanup(srv.Close)

	// The server's own cert is generated by httptest; trust it, and present
	// the client cert the CA signed.
	serverPool := x509.NewCertPool()
	serverPool.AddCert(srv.Certificate())
	client := &http.Client{Transport: &http.Transport{TLSClientConfig: &tls.Config{
		RootCAs: serverPool,
		Certificates: []tls.Certificate{{
			Certificate: [][]byte{clientDER, caDER},
			PrivateKey:  clientKey,
		}},
	}}}
	return srv, client, ids, oks
}

func TestMTLSIdentifiesAVerifiedClientCertificate(t *testing.T) {
	srv, client, ids, oks := mtlsHarness(t, "agent-workstation", []string{"jam@example.com"})
	resp, err := client.Get(srv.URL + "/api/notes")
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()

	id, ok := <-ids, <-oks
	if !ok {
		t.Fatal("a client certificate the CA signed was not identified")
	}
	if id.Subject != "mtls:agent-workstation" {
		t.Errorf("subject = %q, want mtls:agent-workstation", id.Subject)
	}
	if id.User != "jam@example.com" {
		t.Errorf("user = %q, want the certificate's email SAN", id.User)
	}
	if !id.Verified {
		t.Error("the TLS stack verified this chain; the identity must say so")
	}
}

func TestMTLSDoesNotIdentifyAPlainConnection(t *testing.T) {
	// A request with no TLS at all: the ordinary case on a loopback listener.
	if _, ok := (&MTLS{}).Identify(netip.MustParseAddr("127.0.0.1"), req("127.0.0.1:1", nil)); ok {
		t.Error("a connection with no client certificate produced an identity")
	}
}

// The property this guards: a certificate the server did not verify is a
// string the caller chose. Go leaves VerifiedChains empty in that case, and a
// backend that read PeerCertificates without checking it would accept any
// self-signed certificate naming anybody.
func TestMTLSRejectsAnUnverifiedCertificate(t *testing.T) {
	r := req("127.0.0.1:1", nil)
	r.TLS = &tls.ConnectionState{PeerCertificates: []*x509.Certificate{{
		Subject: pkix.Name{CommonName: "i-am-the-admin"},
	}}} // no VerifiedChains: this is what tls.RequestClientCert produces
	if _, ok := (&MTLS{}).Identify(netip.MustParseAddr("127.0.0.1"), r); ok {
		t.Error("an unverified client certificate was accepted; anyone could " +
			"self-sign one naming any principal")
	}
}

func TestMTLSCanNameTheCallerFromAnotherField(t *testing.T) {
	srv, client, ids, oks := mtlsHarness(t, "cn-name", []string{"bot@example.com"})
	// Re-run Identify over the same handshake but reading the email field.
	resp, err := client.Get(srv.URL + "/api/notes")
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	<-ids
	<-oks
	// The harness always reads CN; assert the selector directly on a cert.
	cert := &x509.Certificate{
		Subject:        pkix.Name{CommonName: "cn-name"},
		EmailAddresses: []string{"bot@example.com"},
		DNSNames:       []string{"bot.example.com"},
	}
	for field, want := range map[string]string{
		"":      "cn-name",
		"cn":    "cn-name",
		"email": "bot@example.com",
		"dns":   "bot.example.com",
	} {
		if got := certName(cert, field); got != want {
			t.Errorf("field %q named %q, want %q", field, got, want)
		}
	}
}
