import { useEffect, useRef, useState } from 'react';

type ActionReply = { result?: string | string[]; error?: string };

export function AiActions({ title, body, notePath, locked, request, insert, onError }: { title: string; body: string; notePath: string; locked: boolean; onError: (message: string) => void; request: (action: string, text: string) => Promise<ActionReply>; insert: (text: string) => void }) {
  const [menu, setMenu] = useState(false); const [menuAt, setMenuAt] = useState({ top: 0, right: 0 }); const [explaining, setExplaining] = useState(false); const [answer, setAnswer] = useState(''); const button = useRef<HTMLButtonElement>(null);
  const currentPath = useRef(notePath); currentPath.current = notePath;
  useEffect(() => { setMenu(false); setExplaining(false); }, [notePath]);
  useEffect(() => { if (!explaining) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setExplaining(false); }; addEventListener('keydown', close); return () => removeEventListener('keydown', close); }, [explaining]);
  const explain = async () => { if (!body.trim()) return; setMenu(false); setExplaining(true); setAnswer('Explaining this note…'); try { const reply = await request('summarize', body); if (reply.error) throw new Error(reply.error); setAnswer(typeof reply.result === 'string' ? reply.result : 'No explanation returned.'); } catch (reason) { setAnswer(`Could not explain this note: ${reason instanceof Error ? reason.message : String(reason)}`); } };
  const act = async (action: 'summarize' | 'expand' | 'tags') => { if (!body.trim() || locked) return; const sourcePath = notePath; setMenu(false); try { const reply = await request(action, body); if (reply.error) throw new Error(reply.error); if (currentPath.current !== sourcePath) { onError('The AI result was not inserted because you opened a different note.'); return; } if (action === 'tags' && Array.isArray(reply.result)) insert(`\n\n${reply.result.map(tag => `#${tag}`).join(' ')}\n`); else if (typeof reply.result === 'string') insert(`\n\n---\n${reply.result}\n`); } catch (reason) { onError(`AI action failed: ${reason instanceof Error ? reason.message : String(reason)}`); } };
  return <><button ref={button} id="ai-btn" className="icon" title="AI actions" disabled={locked || !body.trim()} onClick={() => { const rect = button.current?.getBoundingClientRect(); if (rect) setMenuAt({ top: rect.bottom + 4, right: innerWidth - rect.right }); setMenu(value => !value); }}>✦</button>{menu && <div id="ai-menu" className="menu" style={{ position: 'fixed', top: menuAt.top, right: menuAt.right, left: 'auto', zIndex: 10001 }}><button className="mi" data-a="explain" onClick={() => void explain()}>Explain this note</button><button className="mi" data-a="summarize" onClick={() => void act('summarize')}>Summarize</button><button className="mi" data-a="expand" onClick={() => void act('expand')}>Expand draft</button><button className="mi" data-a="tags" onClick={() => void act('tags')}>Suggest tags</button></div>}{explaining && <div id="explain-modal" className="modal" role="dialog" aria-label="Note explained" onMouseDown={event => event.currentTarget === event.target && setExplaining(false)}><div className="modal-box"><button id="explain-close" className="icon modal-close" aria-label="Close explanation" onClick={() => setExplaining(false)}>✕</button><h2 id="explain-title">Note explained</h2><p id="explain-source" className="ask-hint">{title}</p><div id="explain-answer" role="status">{answer}</div></div></div>}</>;
}
