import { useEffect, useRef, useState } from 'react';

type Citation = { path: string; title: string; score?: number };
type Answer = { answer: string; citations: Citation[]; supported?: string };

export function AskPanel({ active, ask, open, close }: { active: boolean; ask: (question: string, includePrivate: boolean) => Promise<Answer>; open: (path: string) => void | Promise<void>; close: () => void }) {
  const [question, setQuestion] = useState(''); const [includePrivate, setIncludePrivate] = useState(false); const [result, setResult] = useState<Answer>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { if (active) input.current?.focus(); }, [active]);
  const run = async () => { if (!question.trim() || busy) return; setBusy(true); setError(''); setResult(undefined); try { setResult(await ask(question.trim(), includePrivate)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not search notes.'); } finally { setBusy(false); } };
  if (!active) return null;
  return <div id="ask-modal" className="modal" role="dialog" aria-label="Ask your notes" onMouseDown={event => event.currentTarget === event.target && close()}><div className="modal-box"><button id="ask-close" className="icon modal-close" aria-label="Close question" onClick={close}>✕</button><h2>Ask your notes</h2><p className="ask-hint">Get an answer from your notes, with links to the sources.</p><div className="ask-input-row"><input ref={input} id="ask-q" aria-label="Your question" value={question} onChange={event => setQuestion(event.target.value)} onKeyDown={event => event.key === 'Enter' && void run()} placeholder="e.g. How do I roll back a deployment?" /><button id="ask-go" className="btn" disabled={!question.trim() || busy} onClick={() => void run()}>{busy ? 'Thinking…' : 'Ask'}</button></div><label className="ask-scope">Search in <select id="ask-priv" value={includePrivate ? 'all' : 'public'} onChange={event => setIncludePrivate(event.target.value === 'all')}><option value="public">Non-private notes</option><option value="all">All notes, including private</option></select></label><div id="ask-answer" role="status">{busy ? <span className="thinking">thinking…</span> : error || result?.answer || ''}</div><div id="ask-cites">{result?.citations.map(citation => <button className="cite" key={citation.path} onClick={() => { close(); void open(citation.path); }}>↳ {citation.title} {typeof citation.score === 'number' && <span className="sc">{Math.round(citation.score * 100)}%</span>}</button>)}</div></div></div>;
}
