import {useEffect,useMemo,useRef,useState} from 'react';
export function FindBar({body,open,onClose,onEdit,onSelect}:{body:string;open:boolean;onClose:()=>void;onEdit:(value:string)=>void;onSelect:(from:number,to:number)=>void}){
 const input=useRef<HTMLInputElement>(null),[query,setQuery]=useState(''),[replacement,setReplacement]=useState(''),[current,setCurrent]=useState(-1);
 const matches=useMemo(()=>{const result:number[]=[];if(query){let at=0;while((at=body.indexOf(query,at))>=0){result.push(at);at+=query.length;}}return result;},[body,query]);
 useEffect(()=>{if(open)input.current?.focus();},[open]);
 const move=(direction:number)=>{if(!matches.length)return;const index=(current+direction+matches.length)%matches.length;setCurrent(index);onSelect(matches[index]!,matches[index]!+query.length);};
 if(!open)return null;
 return <div id="find-bar" className="find-bar" hidden={!open} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();}}}><input ref={input} id="find-input" placeholder="Find" value={query} onChange={e=>{setQuery(e.target.value);setCurrent(-1);}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();move(e.shiftKey?-1:1);}if(e.key==='Escape')onClose();}}/><span id="find-count">{matches.length}</span><button className="icon" id="find-prev" title="Previous match" onClick={()=>move(-1)}>↑</button><button className="icon" id="find-next" title="Next match" onClick={()=>move(1)}>↓</button><input id="replace-input" placeholder="Replace" value={replacement} onChange={e=>setReplacement(e.target.value)}/><button className="btn" id="find-replace" disabled={!matches.length} onClick={()=>{const index=Math.max(0,Math.min(current,matches.length-1)),at=matches[index];if(at===undefined)return;onEdit(body.slice(0,at)+replacement+body.slice(at+query.length));setCurrent(index-1);}}>Replace</button><button className="btn" id="find-all" disabled={!matches.length} onClick={()=>{if(query)onEdit(body.split(query).join(replacement));setCurrent(-1);}}>All</button><button className="icon" id="find-close" aria-label="Close find" onClick={onClose}>✕</button></div>;
}
