import { useRef, useState } from 'react';
import type { Note } from './types';

export function HoverPreview({ children, note, onError }: { children: React.ReactNode; note: (path: string) => Promise<Note>; onError?: (message: string) => void }) {
  const [preview, setPreview] = useState<{ title: string; body: string; x: number; y: number }>();
  const showTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined); const hideTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined); const cache = useRef(new Map<string, Note>());
  const clear = () => { if (showTimer.current) clearTimeout(showTimer.current); if (hideTimer.current) clearTimeout(hideTimer.current); };
  const schedule = (anchor: HTMLAnchorElement) => { clear(); showTimer.current = setTimeout(() => { const path = decodeURIComponent(anchor.getAttribute('href')?.replace(/^#/, '') || ''); if (!path) return; const load = cache.current.get(path) ? Promise.resolve(cache.current.get(path)!) : note(path).then(result => { cache.current.set(path, result); return result; }); void load.then(result => { const rect = anchor.getBoundingClientRect(); setPreview({ title: result.title || result.path, body: result.body.replace(/^#\s.*$/m, '').trim().slice(0, 280), x: Math.min(rect.left, window.innerWidth - 340), y: Math.min(rect.bottom + 6, window.innerHeight - 220) }); }).catch(e => onError?.(e instanceof Error ? e.message : 'Could not open note preview')); }, 280); };
  return <div className="hover-preview-surface" onMouseOver={e => { const target = (e.target as Element).closest('a.wikilink') as HTMLAnchorElement | null; if (target && !target.classList.contains('unresolved')) schedule(target); }} onMouseOut={e => { const related = e.relatedTarget as Node | null; if (related && e.currentTarget.contains(related)) return; clear(); hideTimer.current = setTimeout(() => setPreview(undefined), 220); }}>{children}{preview && <aside id="hover-preview" onMouseEnter={clear} onMouseLeave={() => { clear(); hideTimer.current = setTimeout(() => setPreview(undefined), 220); }} style={{ left: preview.x, top: preview.y }}><div className="hp-title">{preview.title}</div><div className="md hp-body">{preview.body}</div></aside>}</div>;
}
