import {createElement,useEffect,useMemo,useState,type ReactNode} from 'react';
import MarkdownIt from 'markdown-it';
import footnote from 'markdown-it-footnote';
import type {Note,NoteListItem,JsonValue} from './types';
import {createGrimoireApi} from './api';
const parser=new MarkdownIt({html:false,linkify:true,breaks:true}).use(footnote);
type Token=ReturnType<typeof parser.parse>[number];
const api=createGrimoireApi();
const keywords=new Set('const let var function func fn return if else elif for while class struct interface type enum import export from package use pub async await new def lambda try except catch finally throw with match case switch break continue in of is not and or public private protected static void int float double string str bool true false True False None null nil self this super impl trait yield do then end module namespace typedef extends implements'.split(' '));
const imagePath=/\.(?:png|jpe?g|gif|webp|svg|avif)(?:\|.*)?$/i;
interface Props {body:string;notes:NoteListItem[];open:(path:string)=>void;tag:(tag:string)=>void;toggleTask?:(line:number)=>void;pluginFence?:(lang:string,source:string)=>ReactNode;depth?:number;offset?:number}
interface QueryResult {render?:string;columns?:string[];rows:Record<string,JsonValue>[];count?:number;errors?:string[]}
function Code({source,lang}:{source:string;lang:string}){const output:ReactNode[]=[];let last=0;const regex=/(\/\/[^\n]*|#[^\n]*|\/\*[\s\S]*?\*\/)|("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`)|(\b\d[\d_.]*(?:[eE][+-]?\d+)?\b)|([A-Za-z_$][\w$]*)/g;for(const match of source.matchAll(regex)){const at=match.index;output.push(source.slice(last,at));const cls=match[1]?'hl-com':match[2]?'hl-str':match[3]?'hl-num':keywords.has(match[4]||'')?'hl-kw':'';output.push(cls?<span key={at} className={cls}>{match[0]}</span>:match[0]);last=at+match[0].length;}output.push(source.slice(last));return <pre><code className={'lang-'+lang} data-lang={lang}>{output}</code></pre>;}
function Query({source,open,tag}:{source:string;open:Props['open'];tag:Props['tag']}){const [result,setResult]=useState<QueryResult>(),[error,setError]=useState('');useEffect(()=>{const abort=new AbortController();setResult(undefined);setError('');void api.request<QueryResult>('/query',{method:'POST',body:{block:source},signal:abort.signal}).then(setResult).catch(e=>{if(!abort.signal.aborted)setError(String(e));});return()=>abort.abort();},[source]);const link=(row:Record<string,JsonValue>)=><a className="wikilink" href={'#'+encodeURIComponent(String(row.path))} onClick={e=>{e.preventDefault();open(String(row.path));}}>{String(row.title||row.path)}</a>;return <div className="query">{error||result?.errors?.join('; ')||(!result?'Running query…':result.render==='count'?<span className="query-count">{result.count}</span>:result.render==='table'?<div className="table-wrap"><table><thead><tr>{result.columns?.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}>{result.columns?.map(c=><td key={c}>{c==='title'?link(row):c==='tags'&&Array.isArray(row.tags)?row.tags.map(t=><button className="tag" key={String(t)} onClick={()=>tag(String(t))}>#{String(t)}</button>):String(row[c]??'')}</td>)}</tr>)}</tbody></table></div>:<ul>{result.rows.map((row,i)=><li key={i}>{link(row)}</li>)}</ul>)}</div>;}
function Embedded({target,props}:{target:string;props:Props}){const [note,setNote]=useState<Note>(),[error,setError]=useState('');const name=target.split('#')[0]!.trim();const path=props.notes.find(n=>[n.path,n.path.replace(/\.md$/,''),n.path.replace(/\.md$/,'').split('/').pop(),n.title].some(v=>v?.toLowerCase()===name.toLowerCase()))?.path;useEffect(()=>{const abort=new AbortController();setNote(undefined);setError('');if((props.depth||0)>=2)return;void (async()=>{const resolved=path||(await api.aliases(abort.signal))[name.toLowerCase()];if(!resolved)throw new Error('Note not found');setNote(await api.note(resolved,abort.signal));})().catch(e=>{if(!abort.signal.aborted)setError(String(e));});return()=>abort.abort();},[path,name,props.depth]);return <div className="embed">{(props.depth||0)>=2?'Embed depth limit':error||(!note?'Loading '+target+'…':note.locked?'🔒 '+target:<><div className="embed-title"><a className="wikilink" href={'#'+encodeURIComponent(note.path)} onClick={e=>{e.preventDefault();props.open(note.path);}}>{note.title}</a></div><Markdown {...props} body={note.body} depth={(props.depth||0)+1} toggleTask={undefined}/></>)}</div>;}
const safeURL=(url:string)=>!/^\s*(?:javascript|vbscript|data):/i.test(url)?url:'#';
export function Markdown(props:Props){const {notes,open,tag,pluginFence,toggleTask,offset=0}=props;
 const body=useMemo(()=>{const fences:string[]=[];return props.body.replace(/```[\s\S]*?```/g,part=>`\u0000FENCE${fences.push(part)-1}\u0000`).replace(/%%[\s\S]*?%%/g,'').replace(/\u0000FENCE(\d+)\u0000/g,(_,index:string)=>fences[Number(index)]||'');},[props.body]);
 const tokens=useMemo(()=>parser.parse(body,{}),[body]);
 const text=(value:string,key:string):ReactNode=>value.split(/(!?\[\[[^\]]+\]\]|==[^=]+==|#[A-Za-z][\w/-]*)/g).map((part,index)=>{const id=key+'-'+index,wiki=/^(!?)\[\[([^|\]]+)(?:\|([^\]]+))?\]\]$/.exec(part);if(wiki){const target=wiki[2]!,label=wiki[3]||target;if(wiki[1])return imagePath.test(target)?<img key={id} className="embed" src={'/api/file/'+target.split('/').map(encodeURIComponent).join('/')} alt={label}/>:<Embedded key={id} target={target} props={props}/>;const name=target.split('#')[0]!;const path=notes.find(n=>[n.path,n.title,n.path.replace(/\.md$/,''),n.path.replace(/\.md$/,'').split('/').pop()].some(v=>v?.toLowerCase()===name.toLowerCase()))?.path||target;return <a key={id} className="wikilink" href={'#'+encodeURIComponent(path)} onClick={e=>{e.preventDefault();open(path);}}>{label}</a>;}if(part.startsWith('==')&&part.endsWith('=='))return <mark key={id}>{part.slice(2,-2)}</mark>;if(/^#[A-Za-z]/.test(part))return <button key={id} className="tag" onClick={()=>tag(part.slice(1))}>{part}</button>;return part;});
 const render=(items:Token[],parentLine=0,task=false):ReactNode[]=>{const result:ReactNode[]=[];for(let i=0;i<items.length;i++){const token=items[i]!;if(token.nesting===-1)continue;const key=String(i),line=token.map?.[0]??parentLine;
 if(token.type==='inline'){result.push(<span key={key}>{render(token.children||[],line,task)}</span>);continue;}
 if(token.type==='text'){result.push(<span key={key}>{text(task&&i===0?token.content.replace(/^\[[ xX]\]\s*/, ''):token.content,key)}</span>);continue;}
 if(token.type==='fence'||token.type==='code_block'){const lang=token.info.trim().split(/\s/)[0]||'';result.push(<div key={key}>{lang==='query'?<Query source={token.content} open={open} tag={tag}/>:pluginFence?.(lang,token.content)||<Code source={token.content} lang={lang}/>}</div>);continue;}
 if(token.type==='footnote_ref'){const id=(token.meta as {id:number}).id;result.push(<sup className="fn-ref" key={key}><a href={'#fn-'+id}>{id+1}</a></sup>);continue;}
 if(token.type==='footnote_anchor'){continue;}
 if(token.type==='softbreak'||token.type==='hardbreak'){result.push(<br key={key}/>);continue;}
 if(token.type==='code_inline'){result.push(<code key={key}>{token.content}</code>);continue;}
 if(token.type==='image'){result.push(<img key={key} src={safeURL(String(token.attrGet('src')||''))} alt={token.content}/>);continue;}
 if(token.nesting===1){let end=i+1,level=1;for(;end<items.length;end++){level+=items[end]!.nesting;if(level===0)break;}const inner=items.slice(i+1,end);i=end;
 if(token.type==='blockquote_open'){const block=body.split('\n').slice(token.map?.[0]||0,token.map?.[1]||0).map(l=>l.replace(/^\s*>\s?/,''));const callout=/^\[!([\w-]+)\]\s*(.*)$/.exec(block[0]||'');if(callout){result.push(<aside key={key} className={'callout callout-'+callout[1]}><div className="callout-title">{callout[2]||callout[1]}</div><Markdown {...props} body={block.slice(1).join('\n')} offset={offset+line+1}/></aside>);continue;}}
 const embedded=token.tag==='p'?/^!\[\[([^\]]+)\]\]$/.exec(inner.find(t=>t.type==='inline')?.content.trim()||''):null;if(embedded){const target=embedded[1]!;result.push(imagePath.test(target)?<img key={key} className="embed" src={'/api/file/'+target.split('/').map(encodeURIComponent).join('/')} alt={target}/>:<Embedded key={key} target={target} props={props}/>);continue;}
 const isTask=token.tag==='li'&&/^\s*[-*+]\s+\[([ xX])\]/.test(body.split('\n')[line]||'');const checked=/^\s*[-*+]\s+\[[xX]\]/.test(body.split('\n')[line]||'');let tagName=token.tag||'div';const attributes:Record<string,unknown>={key};if(token.type==='footnote_block_open'){tagName='ol';attributes.className='footnotes';}if(token.type==='footnote_open'){tagName='li';attributes.id='fn-'+(token.meta as {id:number}).id;}
 if(/^h[1-6]$/.test(tagName)){attributes.id='h-'+(inner.find(t=>t.type==='inline')?.content||'heading').trim().toLowerCase().replace(/[^\w\s-]/g,'').replace(/[\s_]+/g,'-');}
 if(tagName==='a'){const href=safeURL(String(token.attrGet('href')||''));attributes.href=href;if(/^https?:/i.test(href)){attributes.target='_blank';attributes.rel='noopener noreferrer';}}
 if(isTask)attributes.className=checked?'task done':'task';const children=render(inner,line,isTask||task);result.push(createElement(tagName,attributes,isTask?<input type="checkbox" className="task-box" checked={checked} onChange={()=>toggleTask?.(offset+line)} readOnly={!toggleTask}/>:null,...children));continue;}
 if(token.type==='hr')result.push(<hr key={key}/>);else if(token.content)result.push(<span key={key}>{token.content}</span>);
 }return result;};
 return <div className="md">{render(tokens)}</div>;
}
