import {useEffect,useRef,useState} from 'react';
import type {Note,JsonValue} from './types';
const reserved=new Set(['title','tags','aliases','pinned','private','created','updated','encrypted']);
const list=(value:JsonValue|undefined)=>Array.isArray(value)?value.join(', '):value?String(value):'';
export function NoteProperties({note,onSave,onClose}:{note:Note;onSave:(change:Partial<Note>)=>Promise<boolean>;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[title,setTitle]=useState(note.title),[tags,setTags]=useState(list(note.frontmatter.tags)),[aliases,setAliases]=useState(list(note.frontmatter.aliases)),[pinned,setPinned]=useState(!!note.frontmatter.pinned),[privateNote,setPrivate]=useState(note.private),[custom,setCustom]=useState(Object.entries(note.frontmatter).filter(([key])=>!reserved.has(key)).map(([key,value])=>({key,value:typeof value==='object'?JSON.stringify(value):String(value)}))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>previous?.focus();},[]);
 async function submit(){if(busy)return;const fm:Record<string,JsonValue>={};for(const row of custom){if(row.key.trim()&&!reserved.has(row.key.trim()))fm[row.key.trim()]=row.value;}fm.tags=tags.split(',').map(s=>s.trim()).filter(Boolean);fm.aliases=aliases.split(',').map(s=>s.trim()).filter(Boolean);fm.pinned=pinned;fm.private=privateNote;if(note.frontmatter.created)fm.created=note.frontmatter.created;setBusy(true);setError('');try{if(await onSave({title,private:privateNote,frontmatter:fm}))onClose();else setError('Properties could not be saved. Your changes remain here.');}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <dialog ref={dialog} id="props-modal" className="react-note-dialog" onCancel={event=>{if(busy)event.preventDefault();else onClose();}}><header><h2>Note properties</h2><button id="props-close" className="icon" disabled={busy} onClick={onClose} aria-label="Close properties">✕</button></header><form id="props-body" onSubmit={event=>{event.preventDefault();void submit();}}><label className="set-row">Title<input id="pr-title" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="set-row">Tags<input id="pr-tags" value={tags} onChange={e=>setTags(e.target.value)}/></label><label className="set-row">Aliases<input id="pr-aliases" value={aliases} onChange={e=>setAliases(e.target.value)}/></label><div className="set-row pr-flags"><label><input id="pr-pinned" type="checkbox" checked={pinned} onChange={e=>setPinned(e.target.checked)}/> Pinned</label><label><input id="pr-private" type="checkbox" checked={privateNote} onChange={e=>setPrivate(e.target.checked)}/> Private</label></div><h3>Custom fields</h3><div id="pr-custom">{custom.map((row,index)=><div className="pr-crow" key={index}><input className="pr-ck" aria-label="Property name" value={row.key} onChange={e=>setCustom(rows=>rows.map((r,i)=>i===index?{...r,key:e.target.value}:r))}/><input className="pr-cv" aria-label="Property value" value={row.value} onChange={e=>setCustom(rows=>rows.map((r,i)=>i===index?{...r,value:e.target.value}:r))}/><button type="button" className="icon danger pr-del" aria-label="Remove property" onClick={()=>setCustom(rows=>rows.filter((_,i)=>i!==index))}>×</button></div>)}</div><button id="pr-add" className="btn" type="button" onClick={()=>setCustom(rows=>[...rows,{key:'',value:''}])}>+ field</button>{error&&<p role="alert">{error}</p>}<button id="pr-save" className="btn full" type="submit" disabled={busy||note.locked}>{busy?'Saving…':'Save properties'}</button></form></dialog>;
}
