/**
 * One-time build of the vendored editor bundle.
 *
 * Grimoire ships with no runtime build step — the PWA is plain ES modules.
 * The one exception is CodeMirror 6 (the live-preview editor), which is an
 * npm-only ecosystem. This script bundles our editor entry (editor-entry.mjs)
 * plus its pinned CM6 dependencies into a single self-contained ES module at
 * web/vendor/editor.js, which is then checked in like any other source file.
 *
 * Rebuild only when bumping CM6 versions:   cd tools && npm install && npm run build
 */
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [join(here, "editor-entry.mjs")],
  bundle: true,
  format: "esm",
  target: "es2022",
  outfile: join(here, "..", "web", "vendor", "editor.js"),
  minify: true,
  sourcemap: false,
  logLevel: "info",
  banner: {
    js: "// Vendored CodeMirror 6 bundle — generated by tools/build-editor.mjs. Do not edit by hand.",
  },
});
